version: '3.8'

services:
  glpi-middleware:
    build: .
    container_name: glpi_scanner_api
    # Esta línea fuerza a Docker a usar Python, ignorando la caché del Dockerfile viejo
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - GLPI_BASE_URL=${GLPI_BASE_URL}
      - GLPI_CLIENT_ID=${GLPI_CLIENT_ID}
      - GLPI_CLIENT_SECRET=${GLPI_CLIENT_SECRET}
      - GLPI_USERNAME=${GLPI_USERNAME}
      - GLPI_PASSWORD=${GLPI_PASSWORD}
    networks:
      - glpi_network

networks:
  glpi_network:
    driver: bridge